swagger: '2.0'
info:
  title: Endpoint for Lattes number validation
  version: 0.1.0
  description: This endpoint allows you to validate the Lattes identification number.
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /lattes/{lattes_number}:
    get:
      tags:
        - Lattes
      description: Returns whether a lattes identifier number is valid or not.
      parameters:
        - name: lattes_number
          in: path
          description: Lattes id number
          required: true
          type: integer
      responses:
        '200':
          description: Lattes successfully validated
          schema:
            type: object
            properties:
              id_lattes:
                type: integer
                description: Lattes id number.
              message:
                type: string
                description: Validation message.
              status:
                type: boolean
                description: Validation status.
        '404':
          description: Invalid Lattes identification number
          schema:
            type: object
            properties:
              id_lattes:
                type: integer
                description: Lattes id number.
              message:
                type: string
                description: Error message.
              status:
                type: boolean
                description: Validation status.